name: Doctochat Doctors APP DEV CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Create env configs
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> .env        
          echo "${{ secrets.API_PATH_DEV }}" >> .env
          echo "${{ secrets.PUSHER_ENV_DEV }}" >> .env
          echo "${{ secrets.FIREBASE_ENV_DEV }}" >> .env
          echo "VITE_API_PREFIX=md" >> .env

      - name: Install Dependencies with Yarn
        run: yarn install --immutable-cache

      - name: Build
        run: CI=false yarn build

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASS }}
          private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          scp_source: "build/"
          scp_target: ${{ secrets.TARGET_DOCTORS_DEV_APP_MD }}

      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          format: html
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ <b>[DEV] Doctor's APP</b>
            🥷 <b>User</b>: ${{ github.actor }}
            📂 <b>Commit:</b> <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">${{ github.event.commits[0].message }}</a>
            
